CREATE TABLE [dbo].[HR_Attendance_Archive](
    [CompanyCode_R1] [varchar](10) NULL,
    [EmployeeNumber] [varchar](10) NOT NULL, 
    [StartDate] [datetime] NOT NULL,        
    [EndDate_R2] [datetime] NULL,
    [RemovalCode] [varchar](50) NOT NULL,    
    [StatusFlag_R3] [varchar](1) NULL,       
    [Indicator_R4] [varchar](1) NULL,        
    [Date_R5] [datetime] NULL,               
    [ActivityFlag_R6] [varchar](1) NULL,     
    [Minutes_R7] [int] NULL,                 
    [BaseCode_R8] [varchar](3) NULL,         
    [BidFlag_R9] [varchar](1) NULL,          
    [Time_R10] [datetime] NULL,              
    [User_R11] [varchar](50) NULL,           
    [Date_R12] [datetime] NULL,              
    [User_R13] [varchar](50) NULL,           
    [DelFlag_R14] [varchar](1) NULL,         
    [DelDate_R15] [datetime] NULL,           
    [Flag_R16] [varchar](1) NULL,            
    [Date_R17] [datetime] NULL,              
    [W1Flag_R18] [varchar](1) NULL,          
    [W1Date_R19] [datetime] NULL,            
    [W2Flag_R20] [varchar](1) NULL,          
    [W2Date_R21] [datetime] NULL,            
    [TermFlag_R22] [varchar](1) NULL,        
    [TermDate_R23] [datetime] NULL,          
    [Type_R24] [varchar](2) NULL,            
    [ID_R25] [int] NULL,                     
    [Score_R26] [numeric](6, 2) NULL,        
    [Duration_R27] [decimal](18, 2) NULL,    
    [Type_R28] [varchar](10) NULL,           
    [ExFlag_R29] [varchar](1) NULL,          
    [HolidayFlag_R30] [varchar](1) NULL,     
    [PlanFlag_R31] [varchar](1) NULL,        
    [Code_R32] [varchar](1) NULL,            
    [CreditStatus_R33] [varchar](1) NULL,    
    [ReasonCode_R34] [varchar](1) NULL,      
    [ActivityDate_R35] [datetime] NULL,      
    [Length_R36] [int] NULL,                 
    [Note_R37] [varchar](500) NULL,          
    [Reason_R38] [varchar](50) NULL,         
    [Note_R39] [varchar](max) NULL,          
    [Date_R40] [date] NULL,                  
CONSTRAINT [PK_HR_Attendance_Archive] PRIMARY KEY CLUSTERED 
(
    [EmployeeNumber] ASC,
    [StartDate] ASC,
    [RemovalCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
